version: '3.3'
services:
  db:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: 'Admin@123'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123..

